# Generated by Django 5.2.7 on 2025-10-08 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('broker', models.CharField(help_text='e.g., UBS, Barclays, Goldman Sachs', max_length=200)),
                ('ticker', models.CharField(help_text='e.g., NVDA, AAPL, TSLA', max_length=20)),
                ('report_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker Document',
                'verbose_name_plural': 'Broker Documents',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
