# Generated by Django 5.2.7 on 2025-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerdocument',
            name='broker',
            field=models.CharField(blank=True, help_text='e.g., UBS, Barclays, Goldman Sachs', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brokerdocument',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokerdocument',
            name='ticker',
            field=models.CharField(blank=True, help_text='e.g., NVDA, AAPL, TSLA', max_length=20, null=True),
        ),
    ]
