# Generated by Django 5.2.7 on 2025-10-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_brokerdocument_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerdocument',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the file content', max_length=64, null=True, unique=True),
        ),
    ]
